# Generated by Django 5.1.4 on 2025-01-08 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_appointment_payment_status_user_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='payment_status',
        ),
    ]
