# Generated by Django 5.1.4 on 2025-01-08 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_appointment_payment_intent_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='payment_intent_id',
        ),
    ]
