# Generated by Django 5.1.4 on 2025-01-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_doctorpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorpayment',
            name='payment_intent_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
