# Generated by Django 5.1.4 on 2025-01-10 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_doctorpayment_payment_intent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorpayment',
            name='payment_intent_id',
        ),
    ]
